const highSchoolCourses = [
  {
    "name": "Literature and Composition",
    "description": "This course covers classic and modern literary works, as well as developing writing skills.",
    "image": "images/courses/img_image_1.png",
    "instructor": "Kristin Watson",
    "price": 150.00,
    "category": "High School, Language",
    "duration": 16,
    "lessons": 20,
    "quizzes": 5,
    "certificated": true,
    "language": "English",
  },
  {
    "name": "Algebra and Functions",
    "description": "Students will explore algebraic concepts and functions for solving equations and real-world problems.",
    "image": "images/courses/img_image_2.png",
    "instructor": "Brooklyn Simmons",
    "price": 130.00,
    "category": "High School, Mathematics",
    "duration": 16,
    "lessons": 18,
    "quizzes": 6,
    "certificated": true,
    "language": "English",
  },
  {
    "name": "Chemistry in Everyday Life",
    "description": "This course introduces students to chemical reactions and their applications in everyday life.",
    "image": "images/courses/img_image_3.png",
    "instructor": "Robert Fox",
    "price": 140.00,
    "category": "High School, Science",
    "duration": 10,
    "lessons": 22,
    "quizzes": 8,
    "certificated": true,
    "language": "English",
  },
  {
    "name": "World History",
    "description": "A comprehensive look at the major events and cultures that have shaped our world.",
    "image": "images/courses/img_image_4.png",
    "instructor": "Wade Warren",
    "price": 125.00,
    "category": "High School, Social Studies",
    "duration": 14,
    "lessons": 20,
    "quizzes": 6,
    "certificated": true,
    "language": "English",
  },
  {
    "name": "Introduction to Physics",
    "description": "Students will discover the principles of motion, energy, and forces in the natural world.",
    "image": "images/courses/img_image_1.png",
    "instructor": "Kristin Watson",
    "price": 135.00,
    "category": "High School, Science",
    "duration": 10,
    "lessons": 18,
    "quizzes": 7,
    "certificated": true,
    "language": "English",
  },
  {
    "name": "Biology and the Environment",
    "description": "A course that covers the living organisms around us and their interactions with their environments.",
    "image": "images/courses/img_image_2.png",
    "instructor": "Brooklyn Simmons",
    "price": 145.00,
    "category": "High School, Science",
    "duration": 12,
    "lessons": 22,
    "quizzes": 7,
    "certificated": true,
    "language": "English",
  },
  {
    "name": "Physical Education and Wellness",
    "description": "Developing fitness and health knowledge for lifelong wellness.",
    "image": "images/courses/img_image_3.png",
    "instructor": "Robert Fox",
    "price": 120.00,
    "category": "High School, Physical Education",
    "duration": 8,
    "lessons": 16,
    "quizzes": 4,
    "certificated": true,
    "language": "English",
  },
  {
    "name": "Creative Writing Workshop",
    "description": "Students will develop writing skills across genres such as poetry, fiction, and nonfiction.",
    "image": "images/courses/img_image_4.png",
    "instructor": "Wade Warren",
    "price": 140.00,
    "category": "High School, Language",
    "duration": 8,
    "lessons": 20,
    "quizzes": 5,
    "certificated": true,
    "language": "English",
  },
  {
    "name": "Computer Programming Basics",
    "description": "This course covers the foundations of coding and software development, including problem-solving and algorithm design.",
    "image": "images/courses/img_image_1.png",
    "instructor": "Kristin Watson",
    "price": 155.00,
    "category": "High School, Technology",
    "duration": 12,
    "lessons": 24,
    "quizzes": 8,
    "certificated": true,
    "language": "English",
  },
  {
    "name": "Global Citizenship",
    "description": "Students explore current global issues, including culture, diversity, and international relations, to understand and participate in the world as informed citizens.",
    "image": "images/courses/img_image_2.png",
    "instructor": "Brooklyn Simmons",
    "price": 130.00,
    "category": "High School, Social Studies",
    "duration": 8,
    "lessons": 18,
    "quizzes": 6,
    "certificated": true,
    "language": "English",
  }
]

highSchoolCourses.map(async (course) => {
  const response = await fetch('http://localhost:3001/api/v1/course', {
    method: "POST", // *GET, POST, PUT, DELETE, etc.
    headers: {
      "Content-Type": "application/json",
      // 'Content-Type': 'application/x-www-form-urlencoded',
    },
    referrerPolicy: "no-referrer", // no-referrer, *no-referrer-when-downgrade, origin, origin-when-cross-origin, same-origin, strict-origin, strict-origin-when-cross-origin, unsafe-url
    body: JSON.stringify(course), // body data type must match "Content-Type" header
  })
})